Fix version checking
vimeo/psalm pull request #10129
Opened 2023-08-18 17:54 UTC by Nitamet

Resolves #10084 

There are now separate checks for version format and supported versions
If the version is invalid or unsupported, CLI now doesn't throw an error and print the stacktrace, just prints the error message and exits

2023-08-18 20:20 UTC, weirdan commented on src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
> +    private const PHP_SUPPORTED_VERSIONS_REGEX = '^(5\.[456]|7\.[01234]|8\.[012])(\..*)?$';
8.3 is partially supported now, so it would make sense to allow it here as well

2023-08-18 20:28 UTC, weirdan requested changes

2023-08-18 20:28 UTC, weirdan commented on src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
> +        }
`exit(1)` is reserved for when Psalm finds some issues with the codebase it inspects, see https://psalm.dev/docs/running_psalm/command_line_usage/#exit-status
 
Also, this method is used in a lot of tests, and exception is so much more useful in tests compared to outright crash. Please keep the exception, but catch it in `CliUtils::initPhpVersion()` and `exit(2)` there instead.

2023-08-18 21:30 UTC, Nitamet commented
Changed the code according to the comments.

2023-08-18 21:43 UTC, weirdan approved these changes

2023-08-18 21:44 UTC, merged

2023-08-18 21:44 UTC, weirdan commented
Thanks!

2023-08-20 22:13 UTC, weirdan commented on src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
> +        }
Actually it's the other way around. `exit(1)` is for general problems, and `exit(2)` is for successful run that found some code issues.

2023-08-20 22:13 UTC, weirdan commented on src/Psalm/Internal/Analyzer/ProjectAnalyzer.php
> +        }
Sorry for the confusion. I'll fix it myself.