Use same working directory for preparing cache directory as it used in running analysis
vimeo/psalm pull request #3421
Opened 2020-05-21 13:20 UTC by JoshuaBehrens

Imagine the following directory structure
```
.
|____test
| |____phpunit.xml
|____dev-ops
| |____.build
| |____psalm.xml
|____composer.json
|____src
| |____FooBar.php
```
The psalm.xml looks like this:
```xml
<?xml version="1.0"?>
<psalm
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config ../vendor/vimeo/psalm/config.xsd"
    cacheDirectory=".build/psalm"
    errorLevel="1"
    resolveFromConfigFile="true"
>
    <projectFiles>
        <directory name="../src/" />
        <directory name="../test/" />
        <ignoreFiles>
            <directory name="../vendor/" />
        </ignoreFiles>
    </projectFiles>
</psalm>
```
The `dev-ops/.build` directory is intended to contain every temporary files that should not be versioned and are only used to be a file dump for caches and processing.

Like this the cache directory is prepared in `.build/psalm/cachehash1234567890` but every cache writes into `dev-ops/.build/psalm/cachehash1234567890`.

This is due to the fact that the config prepares the cache folder before the working directory is later changed during processing https://github.com/vimeo/psalm/blob/9aa46221f6eb7160ce274af3c8864f13d0ef0e2f/src/psalm.php#L310-L313

The solution is open to discussion as I am unsure whether it should be solved like this on the long run but it works out for me not creating an empty directory at a location it should not write to.

2020-12-04 20:48 UTC, JoshuaBehrens commented
Just a short bumper for others looking for a solution: the current way to fix this is to change the working directory to the directory of the configuration file before executing psalm. Sort of ok but should not be needed

2020-12-04 23:03 UTC, weirdan requested changes

2020-12-04 23:03 UTC, weirdan commented on src/Psalm/Config.php
> +        if ($config->resolve_from_config_file) {
```suggestion
        $cwd = null;
        if ($config->resolve_from_config_file) {
```

2020-12-04 23:03 UTC, weirdan commented on src/Psalm/Config.php
> +        if ($config->resolve_from_config_file) {
```suggestion
        if ($cwd) {
```

2020-12-04 23:04 UTC, weirdan commented
@muglug this looks reasonable. Are there any reasons to not merge this?

2020-12-04 23:23 UTC, JoshuaBehrens commented
Thank you for the review. I'll gonna squash your suggestions :)

2020-12-06 22:56 UTC, JoshuaBehrens commented
I added your suggestions and rebased the code 😁

2020-12-06 23:01 UTC, weirdan approved these changes

2021-07-16 23:36 UTC, merged

2021-07-16 23:36 UTC, weirdan commented
Thanks!

2021-07-17 18:47 UTC, JoshuaBehrens commented
Damn that merge surprised my notifications 😲 I must admit I forgot that I made this change but I exactly know what I'll change in my projects now :) 

thank you for the merge 🙇