add native return types
vimeo/psalm pull request #4116
Opened 2020-09-02 18:22 UTC by orklah

this PR propose adding quite a lot of missing return types.

They were suggested by phpstorm and then refined with psalm running and analysing itself.

If this goes well, I plan to do the same with parameters.

2020-09-02 19:15 UTC, staabm commented
You might automate this refactorings with rector

2020-09-02 19:18 UTC, orklah commented
> You might automate this refactorings with rector

Probably :) I could have done it with psalter too with a tweak or two, but I like how integrated the inspections are in phpstorm. For example, I could choose not to apply types like TCallable(a template in phpdoc) instead of being done and reverted afterwards

2020-09-02 19:21 UTC, staabm commented
Sorry I wasn‘t clear: my suggestion was regarding the future possible Patches you mentioned (nit sure those are supported by phpstorm/psalter)

> If this goes well, I plan to do the same with parameters.
EDIT: I may also propose a PR to get rid of all the redundant phpdoc.

2020-09-02 19:38 UTC, orklah commented
> Sorry I wasn‘t clear: my suggestion was regarding the future possible Patches you mentioned (not sure those are supported by phpstorm/psalter)
> 
> > If this goes well, I plan to do the same with parameters.
> > EDIT: I may also propose a PR to get rid of all the redundant phpdoc.

Oh yeah, I'll try to see which tool is the most effective if I have time! FYI, both native parameter types and redundant phpdoc are supported by phpstorm on last version
For Psalter, it's kind of a hack, The tool won't suggest to add native types if they're already in phpdoc in a lot of cases. However, you can blind it by disabling phpdoc in the config. Psalter will then diligently put every type in signature if possible. The drawback is when there i a more precise type in phpdoc, it will replace it (given it no longer see it). So when I do that, I patch Psalter so it can't modify phpdoc either

2020-09-03 00:12 UTC, muglug commented
Do you know whether or not this affect performance?

2020-09-03 01:20 UTC, weirdan commented
AFAIK for non-object types the effect is negligible: https://3v4l.org/PAW5G/perf#output cf https://3v4l.org/plbip/perf#output

2020-09-03 03:35 UTC, muglug commented
Please remove the unnecessary docblocks as well – at least, a good chunk of them – I'd prefer a single PR

2020-09-03 05:16 UTC, orklah commented
> Do you know whether or not this affects performance?

I remember watching a conference by @nikic which showed that in some case it add additional type checks but in other (rarer) cases it will actually avoid some checks or use specialized opcode instructions and be more effective:
https://youtu.be/JBWgvUrb-q8?t=1588

> Please remove the unnecessary docblocks as well – at least, a good chunk of them – I'd prefer a single PR

Will do!

2020-09-03 11:32 UTC, orklah commented on src/Psalm/FileSource.php
> +    public function getAliases(): Aliases;
Yeah, to be honest, my goal was to cover a large quantity quickly. If I saw an issue with hierarchy or phpdoc or with an issue reported on psalm, I reverted the type. Maybe that's what happened here.

2020-09-03 11:34 UTC, orklah commented
This should be it if the remaining CI pass.

2020-09-03 22:04 UTC, weirdan requested changes

2020-09-03 22:05 UTC, weirdan commented
Note that it is a BC break to introduce a return type in a non-internal non-final class or interface. So this is a good candidate for 4.0 release.

2020-09-03 22:35 UTC, weirdan commented on src/Psalm/Internal/ExecutionEnvironment/BuildInfoCollector.php
> -     * @return $this
@orklah there are several more of these changes below

2020-09-03 22:39 UTC, orklah commented on src/Psalm/Internal/Analyzer/AlgebraAnalyzer.php
>       * @param  StatementsAnalyzer    $statements_analyzer,
oh nicely spotted. The comma was considered by phpstorm as a comment in itself

2020-09-03 22:53 UTC, orklah commented on src/Psalm/Internal/ExecutionEnvironment/BuildInfoCollector.php
> -     * @return $this
fixed as well, thanks

2020-09-04 20:26 UTC, merged

2020-09-04 20:26 UTC, muglug commented
Thanks!