Return types
vimeo/psalm pull request #4176
Opened 2020-09-12 21:03 UTC by orklah

Hi,

In this PR, I had to modify the code a little. Mainly adding return null; or replacing return; by return null; for methods returning types.

2020-09-12 21:29 UTC, orklah commented
Mmh Psalm emit an issue that seems like a false positive. I reverted my edits in this file but the issue remains... I can't even reproduce it locally

2020-09-12 23:08 UTC, weirdan commented
As `$inner_context` is a by-ref param of that method it does indeed look like false positive. Anyway, I have the same issue emitted in an unrelated PR, so it's not something caused by your changes.

2020-09-12 23:18 UTC, weirdan commented
@orklah a lot of `@return`s seems redundant after these changes. Do we have a reason to keep them there?

2020-09-12 23:45 UTC, orklah commented
I removed some of them,, but I kept some of them on purpose:
- When a parent documentation is different than child native return type, Psalm complains that the two are incoherent. Redefining the phpdoc in the child fixes the issue
- A lot of case I fixed where false|null which is more precise than ?bool in signature

2020-09-12 23:46 UTC, orklah commented
> As `$inner_context` is a by-ref param of that method it does indeed look like false positive. Anyway, I have the same issue emitted in an unrelated PR, so it's not something caused by your changes.

oh, yeah, I see that it's on master too. Thanks for noticing

2020-09-13 02:01 UTC, weirdan requested changes

2020-09-13 06:38 UTC, orklah commented on src/Psalm/Type/Atomic.php
> +    ): ?string;
Well spotted, Dropping the parent phpdoc is enough to make psalm stop emitting issues in childs when type don't match.

2020-09-13 12:22 UTC, weirdan approved these changes

2020-09-13 20:39 UTC, merged

2020-09-13 20:39 UTC, muglug commented
Thanks, sorry for breaking master