Add source attribute to checkstyle report
vimeo/psalm pull request #5409
Opened 2021-03-16 19:03 UTC by dsamburskyi

CheckStyle report supports "source" attribute (example [here](https://github.com/checkstyle/checkstyle/blob/e09397dab3c24c294e7559aeb28fcd461b9cd9e1/src/test/resources/com/puppycrawl/tools/checkstyle/ant/checkstyleanttask/ExpectedCheckstyleAntTaskXmlOutput.xml#L4).
CheckStyle parsing tools are getting category and type from the "source" attribute (Jenkins reporting [plugin](https://github.com/jenkinsci/analysis-model/blob/18a6d7cdb4fa1cb485d36a2f328667f171354102/src/main/java/edu/hm/hafner/analysis/parser/checkstyle/CheckStyleParser.java#L88-L99).
This change will allow the reporting tools to define the meta data correctly. See the screenshot from Jenkins with applied change.
![image](https://user-images.githubusercontent.com/25210529/111365260-a81b1500-8668-11eb-8d5e-dd27a756d5a3.png)

2021-03-16 19:49 UTC, muglug commented
Hmm. I never really intended for the parent _classes_ to be part of the public API. 

> This change will allow the reporting tools to define the meta data correctly.

What about using the reporting level as a category instead? Each issue has an assigned reporting level.

2021-03-17 14:27 UTC, dsamburskyi commented
But reporting level is basically `error`, `info`, etc, right? Or am I looking into wrong place?
$reporting_level for all issues from `testCheckstyleReport()` are identical to what's in `severity` attribute. This won't be very helpful as all issues will fall into just few categories.

On the screenshot below is how the report is looking with existing functionality. There's no way to filter issues by it's category or type. For example, someone wants to look at all UnusedClass errors.
<img width="845" alt="image" src="https://user-images.githubusercontent.com/25210529/111482965-c20d3400-870a-11eb-91d7-2d7da221ac09.png">

I'm Ok to try to implement this in a different way if you think this is worth fixing, just need some guidance on where to look at :)

2021-03-20 02:45 UTC, muglug commented
Every issue has an `ERROR_LEVEL` constant that dictates how severe Psalm thinks the issue is: https://github.com/vimeo/psalm/blob/master/src/Psalm/Issue/PossiblyNullIterator.php#L6

2021-07-09 21:52 UTC, caugner commented
@dsamburskyi I think it would be cool to use the `ERROR_LEVEL` as the category, probably even more useful than the parent class. What do you think?

2021-07-09 22:02 UTC, caugner requested changes
LGTM, but it would be nice to use the ERROR_LEVEL.

See: https://github.com/vimeo/psalm/search?q=ERROR_LEVEL+path%3Asrc%2Fpsalm%2FIssue

2021-07-09 22:02 UTC, caugner commented on src/Psalm/Report/CheckstyleReport.php
> +            $issue_source = 'Psalm.' . $parent_issue_type . '.' . $issue_data->type;
```suggestion
            $issue_source = 'Psalm.ErrorLevel' . $error_level. '.' . $issue_data->type;
```

2022-01-20 20:29 UTC, orklah commented
I'll close this as stale, feel free to ping me to reopen

2022-01-20 20:29 UTC, closed without merging