Extract FunctionLikeStorage::setParams()/addParam()
vimeo/psalm pull request #6054
Opened 2021-07-06 09:48 UTC by caugner

Fixes #6050.

2021-07-08 18:37 UTC, caugner commented
@weirdan Is it an acceptable approach to have those methods `setParams()` and `addParam()` on the `FunctionLikeStorage`? Maybe I should mark them as `@internal`?

2021-07-08 19:48 UTC, weirdan requested changes
> Maybe I should mark them as @internal?

Yes, please do.

2021-07-08 22:55 UTC, caugner commented on src/Psalm/Storage/FunctionLikeStorage.php
> +     * @param list<FunctionLikeParameter> $params
```suggestion
     * @internal
     *
     * @param list<FunctionLikeParameter> $params
```

2021-07-08 22:56 UTC, caugner commented on src/Psalm/Storage/FunctionLikeStorage.php
> +
```suggestion

    /**
     * @internal
     */
```

2021-07-09 05:21 UTC, weirdan approved these changes

2021-07-09 05:21 UTC, merged

2021-07-09 05:21 UTC, weirdan commented
Thanks!