Added missing mb_str_split function
vimeo/psalm pull request #6219
Opened 2021-08-01 13:16 UTC by bitwise-operators

Added missing mb_str_split() function from PHP 7.4 to dictionaries

Fixes #6217

2021-08-01 13:24 UTC, orklah commented
Awesome!

Is there a reason why you called the second parameter "limit"? the doc seem to say "length" https://www.php.net/manual/en/function.mb-str-split.php

2021-08-01 13:28 UTC, weirdan requested changes

2021-08-01 13:28 UTC, weirdan commented on dictionaries/CallMap.php
> +'mb_str_split' => ['list<string>', 'string'=>'string', 'limit='=>'int', 'encoding='=>'string|null'],
```suggestion
'mb_str_split' => ['list<string>', 'string'=>'string', 'length='=>'int', 'encoding='=>'string|null'],
```

2021-08-01 13:28 UTC, weirdan commented on dictionaries/CallMap_74_delta.php
> +    'mb_str_split' => ['list<string>', 'string'=>'string', 'limit='=>'int', 'encoding='=>'string|null'],
```suggestion
    'mb_str_split' => ['list<string>', 'string'=>'string', 'length='=>'int', 'encoding='=>'string|null'],
```

2021-08-01 13:37 UTC, weirdan approved these changes

2021-08-01 13:54 UTC, bitwise-operators commented
> Is there a reason why you called the second parameter "limit"? the doc seem to say "length" https://www.php.net/manual/en/function.mb-str-split.php

Oops, well spotted. I copy-pasted part of the signature from mb_split() and missed the difference in name.

2021-08-01 14:05 UTC, orklah commented
It didn't used to matter but now with PHP 8's named parameter, it does :). Thanks for the PR!

2021-08-01 15:11 UTC, merged

2021-08-01 15:11 UTC, weirdan commented
Thanks!

2021-08-17 09:05 UTC, VincentLanglet commented
I think it can be improved https://github.com/vimeo/psalm/pull/6324