Fix mysqli_fetch_* stubs
vimeo/psalm pull request #7014
Opened 2021-11-28 11:18 UTC by kamil-tekiela

I have just noticed during testing that I have specified the wrong type in the previous PR. While correcting it, I also decided to provide more specific types. I am not sure if the types for `mysqli_fetch_array()` works this way, but I hope it does.

2021-11-28 11:21 UTC, orklah commented
Can you use the occasion to fix the indentation in mysqli stub? :)

2021-11-28 13:42 UTC, kamil-tekiela commented
I fixed the indentation and I have also decided to properly specify the type. The type is taken from `fetch_column()` - false. In the case of MYSQLI_NUM it will be a list. In the case of `fetch_all()` it is always a list of one of the three options. 

I have also noticed I forgot to fix `fetch_fields()`

2021-11-28 22:35 UTC, weirdan requested changes

2021-11-28 22:35 UTC, weirdan commented on dictionaries/CallMap.php
> +'mysqli_fetch_all\'2' => ['list<list<null|int|float|string>>', 'result'=>'mysqli_result', 'mode='=>'MYSQLI_NUM'],
Psalm does not support non-class constants as argument types (they can't be syntactically distinguished from class names), so you'd need to use their values instead.

2021-11-29 00:28 UTC, weirdan approved these changes

2021-11-29 00:28 UTC, merged

2021-11-29 00:28 UTC, weirdan commented
Thanks!