[FEATURE] Allow to intercept adding issue in IssueBuffer
vimeo/psalm pull request #7530
Opened 2022-01-30 15:33 UTC by ohader

This change introduces new `BeforeAddIssueEvent` which is invoked
from `IssueBuffer::add`, which allows to collect and intercept code
issue in a generic way.

Resolves: #7528

2022-01-30 17:10 UTC, orklah approved these changes

2022-01-30 18:28 UTC, ohader commented on src/Psalm/Plugin/EventHandler/Event/BeforeAddIssueEvent.php
> +class BeforeAddIssueEvent
should be `final`

2022-01-30 18:30 UTC, ohader commented on src/Psalm/Plugin/EventHandler/Event/BeforeAddIssueEvent.php
> +class BeforeAddIssueEvent
✅

2022-01-30 21:55 UTC, weirdan requested changes

2022-01-30 21:55 UTC, weirdan commented on src/Psalm/Plugin/EventHandler/Event/BeforeAddIssueEvent.php
> +    public function __construct(CodeIssue $issue, bool $fixable)
```suggestion
    /** @internal */
    public function __construct(CodeIssue $issue, bool $fixable)
```

2022-01-30 21:55 UTC, weirdan commented on src/Psalm/Plugin/EventHandler/BeforeAddIssueInterface.php
> +     * Called before adding a code issue.
```suggestion
     * Called before adding a code issue.
     *
     * Note that event handlers are called in the order they were registered, and thus
     * the handler registered earlier may prevent subsequent handlers from running by
     * returning a boolean value.
```

2022-01-31 08:36 UTC, weirdan approved these changes

2022-01-31 08:36 UTC, merged

2022-01-31 08:36 UTC, weirdan commented
Thanks!