Resolve __DIR__ / __FILE__ when const/variable is used for include
vimeo/psalm pull request #7585
Opened 2022-02-04 18:40 UTC by tomasz-kusy

https://github.com/vimeo/psalm/issues/7584

2022-02-04 19:19 UTC, weirdan requested changes

2022-02-04 19:19 UTC, weirdan commented on src/Psalm/Internal/Analyzer/Statements/Expression/MagicConstAnalyzer.php
> +                Type::getString(\dirname($statements_analyzer->getSource()->getFilePath()))
Please import `dirname()` with `use function dirname;` and drop the backslash.

2022-02-04 19:36 UTC, orklah commented
Thanks! Congrats for your first PR!

2022-02-04 19:36 UTC, weirdan approved these changes

2022-02-04 19:36 UTC, merged

2022-02-04 19:36 UTC, weirdan commented
Thanks!

2022-02-22 20:42 UTC, VincentLanglet commented
Now `__DIR__` is resolved, I ends with multiple errors similar to the issue
https://github.com/vimeo/psalm/issues/3886 with the code
```
if (file_exists($file = __DIR__.'/custom_bootstrap.php')) {
    require_once $file;
}
```
Wouldn't it be possible for psalm to not report an error in this situation ?

Since the file with the code is autogenerated, and sometimes there is a custom_bootstrap, sometimes there isn't, I cannot add a psalm-suppress comment (because it will sometimes be reported as unused). 
Any recommendation in this situation @orklah ?

2022-02-22 21:03 UTC, orklah commented
Probably related to https://github.com/vimeo/psalm/issues/3241 and https://github.com/vimeo/psalm/issues/4788

If the expression is too complex, Psalm can't see you're requiring the same thing.

If you have control over the code generation, consider introducing a local variable before the file_exists, this may help