Add property typehints in Internal directory
vimeo/psalm pull request #8897
Opened 2022-12-14 02:52 UTC by jack-worman

Added more property typehints but just for in the Internal directory to ensure BC.

I then used php-cs-fixer to clean up redundant phpdocs.

2022-12-14 06:05 UTC, weirdan requested changes

2022-12-14 14:05 UTC, jack-worman commented on .php-cs-fixer.dist.php
> +        'phpdoc_trim' => true,
To the best of my knowledge CodeSniffer does not have an equivalent rule for many php-cs-fixer rules, these ones included. CodeSniffer does not even have a centralized list of all their rules with examples... There is https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#squizcommentingfunctioncomment but I think this is just the list of rules that can be customized.

In general, I think php-cs-fixer is better: documentation, configuration, and can always automatically fix CS. If you are still opposed I can remove it, but keep the changes it provided so far.

2022-12-14 14:30 UTC, weirdan commented on .php-cs-fixer.dist.php
> +        'phpdoc_trim' => true,
> To the best of my knowledge CodeSniffer does not have an equivalent rule for many php-cs-fixer rules, these ones included. CodeSniffer does not even have a centralized list of all their rules with examples... 

It depends on the specific ruleset used (and you can mix and match them too). Many advanced rules are available in `slevomat/coding-standard` (https://github.com/slevomat/coding-standard/) that we already use. It has decent documentation and can automatically fix many issues. 

E.g. there's [`SlevomatCodingStandard.Commenting.UselessFunctionDocComment`](https://github.com/slevomat/coding-standard/blob/master/doc/commenting.md#slevomatcodingstandardcommentinguselessfunctiondoccomment-), [`SlevomatCodingStandard.Commenting.EmptyComment`](https://github.com/slevomat/coding-standard/blob/master/doc/commenting.md#slevomatcodingstandardcommentingemptycomment-) and [`SlevomatCodingStandard.Commenting.DocCommentSpacing`](https://github.com/slevomat/coding-standard/blob/master/doc/commenting.md#slevomatcodingstandardcommentingdoccommentspacing-) that should provide a pretty close approximation of what you have configured for php-cs-fixer here.

2022-12-14 18:43 UTC, jack-worman commented
> @jack-worman would you mind running benchmarks against this PR and the master branch? It looks like it could have more performance impact than your previous PR.

```txt
OLD:
256.11s user 20.99s system 342% cpu 1:20.90 total
251.93s user 19.63s system 351% cpu 1:17.33 total
252.73s user 19.57s system 347% cpu 1:18.33 total
254.36s user 19.10s system 350% cpu 1:17.92 total
252.01s user 19.30s system 352% cpu 1:16.94 total
247.46s user 18.03s system 340% cpu 1:17.97 total

NEW:
246.72s user 19.21s system 346% cpu 1:16.84 total
243.94s user 18.63s system 354% cpu 1:14.13 total
244.22s user 18.06s system 357% cpu 1:13.39 total
249.78s user 19.64s system 346% cpu 1:17.82 total
260.73s user 21.50s system 336% cpu 1:23.89 total
255.39s user 19.22s system 354% cpu 1:17.42 total
```
Using eyeball statistics, I would say there is no performance difference.
I ran this on my jobs fairly large codebase.

2022-12-14 19:31 UTC, jack-worman commented on .php-cs-fixer.dist.php
> +        'phpdoc_trim' => true,
Unfortunately, only `SlevomatCodingStandard.Commenting.EmptyComment` was a close approximation.

`SlevomatCodingStandard.Commenting.UselessFunctionDocComment` only gets triggered when the whole docblock is useless, but php-cs-fixer would find individual `@param` tags that were redundant or that param just didn't exist anymore. It also had a bug were it tried to remove list{int, int} even though that provided more information than the array typehint.

SlevomatCodingStandard.Commenting.DocCommentSpacing could do the trimming but the most important part of the php-cs-fixer rules was the removing of non-existent or redundant `@param` or `@var`

2022-12-14 19:40 UTC, jack-worman commented
PR is kinda out of control, so I'll probably split out the CS changes to a new PR when we decide if we will be using php-cs-fixer.

2022-12-14 20:11 UTC, weirdan commented on .php-cs-fixer.dist.php
> +        'phpdoc_trim' => true,
> `SlevomatCodingStandard.Commenting.UselessFunctionDocComment` only gets triggered when the whole docblock is useless, but php-cs-fixer would find individual @param tags that were redundant or that param just didn't exist anymore.

Right, there's another rule that does that: [`SlevomatCodingStandard.TypeHints.ParameterTypeHint`](https://github.com/slevomat/coding-standard/blob/master/doc/type-hints.md#slevomatcodingstandardtypehintsparametertypehint-)

2022-12-14 20:23 UTC, jack-worman commented on .php-cs-fixer.dist.php
> +        'phpdoc_trim' => true,
My bad for not doing a deeper dive of the rules. Do you think I should pull all CS changes to a new PR?

2022-12-15 02:41 UTC, jack-worman commented on .php-cs-fixer.dist.php
> +        'phpdoc_trim' => true,
I have removed php-cs-fixer and am now just using codesniffer!

2022-12-15 04:35 UTC, weirdan approved these changes
LGTM.

@orklah, @danog any objections?

2022-12-15 17:42 UTC, orklah commented
Should we ignore backward compatibiliy checks here?

2022-12-15 19:11 UTC, jack-worman commented
> Should we ignore backward compatibiliy checks here?

Those BC breaks are because those files were missing their `@internal` annotation, even though they were in the `Psalm\Internal` namespace.

2022-12-15 19:37 UTC, danog commented
If there are no performance impacts (and according to your tests performance improved even, were you using opcache? If yes, the typehints might've triggered some optimizations), LGTM!

2022-12-15 20:11 UTC, merged

2022-12-15 20:11 UTC, orklah commented
Thanks!