Emit warning if the opcache cannot be enabled or JIT cannot be used
vimeo/psalm pull request #9240
Opened 2023-02-07 20:07 UTC by danog

2023-02-07 20:45 UTC, weirdan requested changes

2023-02-07 20:45 UTC, weirdan commented on src/Psalm/Internal/Cli/Psalm.php
> +                . PHP_EOL . PHP_EOL);
Please output it via a `Progress` method, so it can be suppressed.

2023-02-07 20:45 UTC, weirdan commented on src/Psalm/Internal/Cli/Psalm.php
> +                . PHP_EOL . PHP_EOL);
IMO it's not very useful. If someone is running Psalm on PHP 7.x they probably have their reasons why they can't move to 8.x. Nagging them every time Psalm is run is not going to change that.

2023-02-13 02:54 UTC, weirdan commented
@danog I have a version of this PR locally that combines my changes to `PsalmRestarter.php` and yours to `Psalm.php`. I can push it here if you're ok with it.

2023-02-13 08:55 UTC, danog commented
Sure!

2023-02-13 22:35 UTC, weirdan approved these changes

2023-02-13 23:47 UTC, orklah commented
Thanks!

2023-02-13 23:47 UTC, merged