Handle different line endings from baseline.
vimeo/psalm pull request #9566
Opened 2023-03-24 09:53 UTC by DnwK98

This change allows to have different file encoding in baseline and PHP file. This is issue when working in multi-platform team, generating baseline on Linux, and trying to run code analysis on Windows.

Fixes #9239

2023-03-24 15:08 UTC, weirdan commented
Do you think this would fix #9239?

2023-03-24 15:53 UTC, DnwK98 commented
Yes, I reproduced it.

baseline:
```
  <file src="src/Psalm/Config/ProjectFileFilter.php">
    <DocblockTypeContradiction>
      <code>-1</code>
    </DocblockTypeContradiction>
    <InvalidReturnStatement>
      <code>$filter&#13;
            ?? -1&#13;</code>
    </InvalidReturnStatement>
```

code (LF encoded):
```
    public static function loadFromXMLElement(
        SimpleXMLElement $e,
        string $base_dir,
        bool $inclusive
    ): ProjectFileFilter {
        ...

        return $filter
            ?? -1;
    }
```

Before change:
```
ERROR: InvalidReturnStatement - src/Psalm/Config/ProjectFileFilter.php:35:16 - The inferred type '-1|Psalm\Config\ProjectFileFilter' does not match the declared return type 'Psalm\Config\ProjectFileFilter' for Psalm\Config\ProjectFileFilter::loadFromXMLElement (see https://psalm.dev/128)
        return $filter
            ?? -1;


------------------------------
1 errors found
------------------------------
```

After change:
```
------------------------------
                              
       No errors found!       
                              
------------------------------
```

2023-03-24 17:09 UTC, weirdan requested changes
Please add a test showing that baselines generated with older Psalm versions (so, including `\r\n`) would still work once this gets merged.

2023-03-29 21:38 UTC, merged

2023-03-29 21:38 UTC, orklah commented
Thanks!